source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
use_frameworks!

platform :ios, '12.0'

target 'XHudManager_Example' do
  pod 'XHudManager', :path => '../'

  target 'XHudManager_Tests' do
    inherit! :search_paths

  end
end
