use_frameworks!

platform :ios, '8.0'

target 'XHudManager_Example' do
  pod 'XHudManager', :path => '../'

  target 'XHudManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
